### PR TITLE
Use GCC/Clang Endianness Check

### PR DESCRIPTION
**Pull request by AlainODea**
- Use __BYTE_ORDER__ if present

Replaces #10.

### CODE REVIEW

**Comment by AlainODea** [comment]
@kgardas can you check if this correctly picks up big endian on Solaris 11 UltraSPARC?

Here's the procedure I use to build and test:

```bash
cabal sandbox init
cabal install test-framework-hunit
cabal build
cd tests/
make
```

This was the output I got:

```plain
ghc -O ../cbits/double.c ../cbits/float.c -lm \
	    -i. -i.. Tests.hs --make -o test-ieee
[1 of 3] Compiling Numeric.IEEE     ( ../Numeric/IEEE.hs, ../Numeric/IEEE.o )
[2 of 3] Compiling Data.AEq         ( ../Data/AEq.hs, ../Data/AEq.o )
[3 of 3] Compiling Main             ( Tests.hs, Tests.o )
Linking test-ieee ...
./test-ieee
IEEE:
  infinity:
    D1: [OK]
    D2: [OK]
    F1: [OK]
    F2: [OK]
  minNormal:
    D: [OK]
    F: [OK]
  maxFinite:
    D: [OK]
    F: [OK]
  epsilon:
    D: [OK]
    F: [OK]
  copySign:
    D1: [OK]
    D2: [OK]
    D3: [OK]
    D4: [OK]
    D5: [OK]
    D6: [OK]
    F1: [OK]
    F2: [OK]
    F3: [OK]
    F4: [OK]
    F5: [OK]
    F6: [OK]
  succIEEE:
    nan D: [OK]
    neg D1: [OK]
    neg D2: [OK]
    neg D3: [OK]
    neg denorm D1: [OK]
    neg denorm D2: [OK]
    neg denrom D3: [OK]
    zero D1: [OK]
    zero D2: [OK]
    pos denorm D1: [OK]
    pos denorm D2: [OK]
    pos D1: [OK]
    pos D2: [OK]
    pos D3: [OK]
    nan F: [OK]
    neg F1: [OK]
    neg F2: [OK]
    neg F3: [OK]
    neg denorm F1: [OK]
    neg denorm F2: [OK]
    neg denrom F3: [OK]
    zero F1: [OK]
    zero F2: [OK]
    pos denorm F1: [OK]
    pos denorm F2: [OK]
    pos F1: [OK]
    pos F2: [OK]
    pos F3: [OK]
  predIEEE:
    D: [OK]
    F: [OK]
  bisectIEEE:
    D1: [OK]
    D2: [OK]
    D3: [OK]
    D4: [OK]
    D5: [OK]
    D6: [OK]
    D7: [OK]
    D8: [OK]
    D9: [OK]
    F1: [OK]
    F2: [OK]
    F3: [OK]
    F4: [OK]
    F5: [OK]
    F6: [OK]
    F7: [OK]
    F8: [OK]
    F9: [OK]
  sameSignificandBits:
    exact D1: [OK]
    exact D2: [OK]
    exact D3: [OK]
    exact D4: [OK]
    fewbits D1: [OK]
    fewbits D2: [OK]
    fewbits D3: [OK]
    fewbits D4: [OK]
    fewbits D5: [OK]
    fewbits D6: [OK]
    fewbits D7: [OK]
    close D1: [OK]
    close D2: [OK]
    close D3: [OK]
    close D4: [OK]
    close D5: [OK]
    2factors D1: [OK]
    2factors D2: [OK]
    2factors D3: [OK]
    2factors D4: [OK]
    extreme D1: [OK]
    extreme D2: [OK]
    extreme D3: [OK]
    extreme D4: [OK]
    extreme D5: [OK]
    extreme D6: [OK]
    exact F1: [OK]
    exact F2: [OK]
    exact F3: [OK]
    exact F4: [OK]
    fewbits F1: [OK]
    fewbits F2: [OK]
    fewbits F3: [OK]
    fewbits F4: [OK]
    fewbits F5: [OK]
    fewbits F6: [OK]
    fewbits F7: [OK]
    close F1: [OK]
    close F2: [OK]
    close F3: [OK]
    close F4: [OK]
    close F5: [OK]
    2factors F1: [OK]
    2factors F2: [OK]
    2factors F3: [OK]
    2factors F4: [OK]
    extreme F1: [OK]
    extreme F2: [OK]
    extreme F3: [OK]
    extreme F4: [OK]
    extreme F5: [OK]
    extreme F6: [OK]
  maxNum:
    D1: [OK]
    D2: [OK]
    D3: [OK]
    D4: [OK]
    D5: [OK]
    F1: [OK]
    F2: [OK]
    F3: [OK]
    F4: [OK]
    F5: [OK]
  minNum:
    D1: [OK]
    D2: [OK]
    D3: [OK]
    D4: [OK]
    D5: [OK]
    F1: [OK]
    F2: [OK]
    F3: [OK]
    F4: [OK]
    F5: [OK]
  maxNaN:
    D1: [OK]
    D2: [OK]
    D3: [OK]
    D4: [OK]
    D5: [OK]
    F1: [OK]
    F2: [OK]
    F3: [OK]
    F4: [OK]
    F5: [OK]
  minNaN:
    D1: [OK]
    D2: [OK]
    D3: [OK]
    D4: [OK]
    D5: [OK]
    F1: [OK]
    F2: [OK]
    F3: [OK]
    F4: [OK]
    F5: [OK]
  nan:
    D: [OK]
    F: [OK]
  nanWithPayload:
    D1: [OK]
    D2: [OK]
    F1: [OK]
    F2: [OK]
  maxNaNPayload:
    D: [OK]
    F: [OK]
  nanPayload:
    D1: [OK]
    D2: [OK]
    D3: [OK]
    F1: [OK]
    F2: [OK]
    F3: [OK]

         Test Cases    Total        
 Passed  176           176          
 Failed  0             0            
 Total   176           176
```

**Comment by patperry** [comment]
I merged this commit, then cleaned up the endian detection macros a bit. @AlainODea , can you confirm that this fixes your original problem (IllumOS build)?

**Comment by AlainODea** [comment]
@patperry thank you!  I'll verify master on SmartOS tonight :)

**Comment by AlainODea** [comment]
@patperry it works on SmartOS.  I like the clean up steps you took a lot.  Nice refactoring.

**Comment by patperry** [comment]
Thanks for your help. On hackage now as version 0.7.8.

**Comment by AlainODea** [comment]
Thank you for taking the time to maintain this library for the Haskell community. I appreciate it.

**Comment by patperry** [comment]
Thanks for the feedback, Alain. I'm glad that you're finding the package useful.

**Pull request merged**
