### PR TITLE
IEEE: add minDenormal

### PR DESCRIPTION
**Pull request by minad**

### CODE REVIEW

**Comment by minad** [comment]
oh, i took the value that ghci spits out. we should probably use the value according to the standard

**Comment by patperry** [comment]
Awesome, thanks.

**Comment by minad** [comment]
I rechecked, ghci prints in fact 5e-324. So this is better now.

I added tests for succIEEE. I think it still makes sense to provide this constant for clarity.

**Comment by minad** [comment]
cool thx!

**Pull request merged**
